backend:
  name: git-gateway
  branch: master

local_backend:
  name: file-system
  url: http://localhost:8000/

media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro text, name: intro, widget: text}
          - {label: Image, name: image, widget: image}